server:
  port: 9000
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 175.178.108.7
    port: 5672
    username: admin
    password: admin
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true