server:
  port: 9000
spring:
  #\u7ED9\u9879\u76EE\u6765\u4E2A\u540D\u5B57
  application:
    name: rabbitmq-producer
  #\u914D\u7F6ErabbitMq \u670D\u52A1\u5668
  rabbitmq:
    host: 175.178.108.7
    port: 5672
    username: admin
    password: admin